name: round - Build -> Test
on:
  push:
    branches:
      - main
      - release
  pull_request:
    branches:
      - "**"
jobs:
  build-and-deploy:
    concurrency: ci-graph-${{ github.head_ref || github.run_id }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Install Dependencies for Round
        run: |
          cd round
          pnpm install

      # - name: Setup
      #   run: |
      #     cd round
      #     yarn add @graphprotocol/graph-cli
      #     # yarn prepare:goerli
      #     # yarn codegen

      # - name: Test
      #   run: |
      #     cd round
      #     yarn test
